name: Test Build Envrionment

# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lvCICD:
    # The type of runner that the job will run on
    name: Test lvCICD
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CloneRepo
        uses: actions/checkout@v2.4.2

      - name: TestEnvironment
        uses: LV-APT/lvCICD@documentation_before_release
        with:
          Operation: lvEcho
          Parameter1: "line1"
          Parameter2: "line2"
          Parameter3: "line3"
