name: Test Build Environment

# Controls when the workflow will run
on: [push,workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lvCICD:
    # The type of runner that the job will run on
    name: Test lvCICD
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CloneRepo
        uses: actions/checkout@v3

      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT

      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT

      - id: create-step
        run: echo "abc=a b c" >> $GITHUB_OUTPUT

      - name: use output
        run:
          echo ${{ steps.step1.outputs.test }}
          echo ${{ steps.step2.outputs.test }}
          echo ${{ steps.create-step.outputs.abc }}

      - name: TestEnvironment
        id: lvEcho
        uses: LV-APT/lvCICD@main
        with:
          Operation: lvEcho
          Parameter1: "line1"
          Parameter2: "line2"
          Parameter3: "line3"

      - name: Check output of previous step
        run:
          echo ${{ steps.lvEcho.outputs.Result }}

